### ISSUE TITLE
Subnavigation menu, on mobile, loses its ability to link to a parent page

### ISSUE THREAD

**Issue by rjacobsen0** [thinkshout/bene#322] opened 2019-04-05 20:07 UTC
## Overview

User Experience: When you're on a page that is a leaf in the menu structure your parents menu is shown. The first item in your parent's menu is a link to the parent. But when you're in mobile size the first menu item opens the submenu instead (on Webster Apartments, for example, or on CORI). There is a conflict concerning what a click should do. Should it open the menu or should it take you to the parent page? Both functions are needed. Is there another way to structure this menu?

## This ticket is done when:
- [ ] item
- [ ] item

**Comment by mshaver** [comment] 2019-04-08 14:58
This is a duplicate of #198. Needs design/UX recommendations.

**Closed as completed by mshaver** 2019-04-08 14:58 UTC
