### ISSUE TITLE
Bene: Constrain Container for Wide Screen- issues with formatting etc. 

### ISSUE THREAD

**Issue by juliaford** [thinkshout/bene#331] opened 2019-04-26 21:01 UTC
## Overview
@sarahvleigh can you make a prescription for the container for all pages and breakpoints etc. Per what you showed me all Bene sites are stretching to accommodate all screen sizes which isn't great for the full width elements vs. the wysiwyg and cards etc. 

Also feel free to make recommendations for the hero vs. the full width CTAs in terms of sizing. We will likely need to update this from a platform perspective. 

## This ticket is done when:
- [ ] item
- [ ] item

**Comment by mshaver** [comment] 2019-05-31 21:29
This is a dupe of another issue.

**Closed as completed by mshaver** 2019-05-31 21:29 UTC
Labels: new-requirement, design
